# site settings
title: Environmental Research Group
subtitle: Where Science Meets Policy
email: chicago.erg@gmail.com
description: Interfacing Science and Policy Toward Social Good
baseurl: "/erg" # the subpath of your site, e.g. /blog
url: "https://enviroresearchgroup.github.io" # the base hostname & protocol for your site
author:
street_address: 5801 S. Ellis Ave
city: Chicago
state: IL
zip_code: 60615
country: United States of America
phone: (207) 798-9120

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings
500px_url:
facebook_url: https://www.facebook.com/envirochicago
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/company/environmental-research-group-of-chicago
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
